Feature/environment variables
TheThingsNetwork/integration-azure pull request #4
Opened 2016-11-29 17:35 UTC by AntoineRondelet

2016-11-29 18:41 UTC, FokkeZB approved these changes
CR pass (didn't FR)

2016-11-30 02:38 UTC, johanstokking requested changes

2016-11-30 02:38 UTC, johanstokking commented on examples/simple.js
> +  console.log('[INFO] TTN connected');
Remove, don't try to mimick apex log

2016-11-30 02:38 UTC, johanstokking commented on examples/simple.js
> +const bridge = new ttnazureiot.Bridge();
Leave the variables here, but initialize them from env

2016-11-30 02:38 UTC, johanstokking commented on index.js
> +    const key = checkSetting(process.env.TTI_AZURE_KEY);
Pass them still as parameters, see previous comment, and just check here with `if (!appId || !accessKey || ....)`

2016-12-01 10:58 UTC, johanstokking requested changes

2016-12-01 10:58 UTC, johanstokking commented on index.js
> +      throw new Error("Invalid settings: Could not get the setting")
`Invalid arguments`

2016-12-01 15:23 UTC, johanstokking approved these changes

2016-12-01 15:23 UTC, merged