Added the dockerfile to run the bridge
TheThingsNetwork/integration-azure pull request #8
Opened 2016-12-06 16:47 UTC by AntoineRondelet

See issue #5

2016-12-15 10:06 UTC, johanstokking requested changes

2016-12-15 10:06 UTC, johanstokking commented on wrapper.sh
> +node usr/azure-integration/examples/simple.js
Why running the simple example?

2016-12-15 10:06 UTC, johanstokking commented on wrapper.sh
> +exit 1
Why always exiting with 1?

2016-12-15 12:03 UTC, johanstokking requested changes

2016-12-15 12:03 UTC, johanstokking commented on server.js
> +var region = 'eu'
Read these from the environment

2016-12-15 12:03 UTC, johanstokking commented on server.js
> +  console.log('[INFO] ', 'Activated: ', e.devEUI);
No need to add spaces; `console.log()` does that for you

2016-12-15 12:03 UTC, johanstokking commented on server.js
> +  console.info('[INFO] ', 'Uplink: ' + JSON.stringify(msg, null, 2));
Be consistent with passing fields by argument or as concatenated strings

2016-12-15 12:03 UTC, johanstokking commented on wrapper.sh
>  printf 'INTEGRATION PROCESS FATAL ERROR: %s\n' "$?"
Print a fatal error when `node` crashes; check its exit status

2016-12-15 13:28 UTC, AntoineRondelet commented on wrapper.sh
>  printf 'INTEGRATION PROCESS FATAL ERROR: %s\n' "$?"
Isn't it already the case @johanstokking ? the bridge is an infinite loop. The only way to reach the print is when a hard exit happened which makes us exit the bridge program. Then I print the fatal error message and print the status

2016-12-27 10:48 UTC, johanstokking commented
Awesome. How big becomes this image in MB?

2016-12-27 11:04 UTC, AntoineRondelet commented
50 MB @johanstokking

2016-12-27 11:09 UTC, johanstokking requested changes

2016-12-27 11:09 UTC, johanstokking commented on wrapper.sh
> +exit 0
Return the exit code here. I now see what this wrapper is for. It should only print the fatal error when the exit code != 0.

On a graceful shutdown (SIGTERM), the process should shutdown with exit 0 and this is not a fatal error. When updating or scaling down, an exit 0 is fine and should not initiate a crash report.

2017-01-18 15:08 UTC, johanstokking approved these changes

2017-01-18 15:09 UTC, merged