Used mqtts with the azure bridge
TheThingsNetwork/integration-azure pull request #9
Opened 2017-01-18 11:07 UTC by AntoineRondelet

2017-01-18 12:37 UTC, johanstokking requested changes

2017-01-18 12:37 UTC, johanstokking commented on bridge.js
> +  const mqttCertPath = process.env.TTN_MQTT_CERT;
Fallback to hardcoded path; ` || '/etc/ttn/mqtt.ca';`

2017-01-18 12:37 UTC, johanstokking commented on bridge.js
> +  console.warn("Fallback to a non-secure connection");
Never do this, this bloats our logs

2017-01-18 12:37 UTC, johanstokking commented on bridge.js
>  const ttnazureiot = require('.');
Keep the `require`s together

2017-01-19 15:13 UTC, johanstokking requested changes

2017-01-19 15:13 UTC, johanstokking commented on bridge.js
> +const mqttCertPath = process.env.TTN_MQTT_CERT || '/etc/ttn/mqtt-ca.pem'
Add `;`

2017-01-19 15:13 UTC, johanstokking commented on bridge.js
>  'use strict';
+ empty line after

2017-01-19 15:13 UTC, johanstokking commented on bridge.js
> +  ca: [ fs.readFileSync(mqttCertPath) ],
Why an array?

2017-01-19 16:56 UTC, AntoineRondelet commented on bridge.js
> +  ca: [ fs.readFileSync(mqttCertPath) ],
It can be an array or a string. `ca<string> | <string[]> | <Buffer> | <Buffer[]>`

2017-01-20 09:31 UTC, johanstokking approved these changes

2017-01-20 09:31 UTC, merged